hl.env("XCURSOR_SIZE",              "24")
hl.env("HYPRCURSOR_SIZE",           "24")
hl.env("LIBVA_DRIVER_NAME",         "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("GBM_BACKEND",               "nvidia-drm")
hl.env("NVD_BACKEND",               "direct")
hl.env("QT_QPA_PLATFORM",           "wayland")
hl.env("QT_QPA_PLATFORMTHEME",      "qt6ct")
