[default_apps]
terminal = "kitty"

[debug]
try_suppress_errors = false
try_suppress_warnings = false
app_paths = ["~/.local/share/applications/"]

[units]
lengths = "meter"
weights = "kg"
volumes = "l"
temperatures = "C"

[appearance]
width = 900
height = 593
gsk_renderer = "cairo"
recolor_icons = false
icon_paths = ["~/.config/sherlock/icons"]
icon_size = 22
search_icon = true
use_base_css = true
status_bar = true

[behavior]
caching = false
cache = "~/.cache/sherlock_desktop_cache.json"
daemonize = false
animate = true
global_prefix = ""
global_flags = ""

[binds]
prev = "None"
next = "None"
modifier = "control"

[files]
fallback = "~/.config/sherlock/fallback.json"
css = "~/.config/sherlock/gruvbox2.css"
alias = "~/.config/sherlock/sherlock_alias.json"
ignore = "~/.config/sherlock/sherlockignore"
